name: Node.js CI

# Triggers the workflow on push or pull request events
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  # Define a job called 'build'
  build:
    # The operating system on which the job will run
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests
    - name: Run tests
      run: npm test
